name: SonarQube analysis

on:
  push:
    branches:
      - main

jobs:
  sonar-scanner:
    runs-on: ubuntu-latest
    env:
      SONARQUBE_SECRET_KEY: ${{ secrets.SONAR_TOKEN }}
      SONARQUBE_HOST: ${{ secrets.SONAR_HOST_URL }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: actions/setup-flutter@latest-version
        with:
          flutter-version: '3.10.6'
      - name: SonarQube analysis
        run: |
          flutter pub get
          flutter analyze
          sonar-scanner -Dsonar.projectKey=UTSelva2023_EduSmart_AYweLX0299VCMeYC9A9f -Dsonar.sources=lib -Dsonar.language=Dart -Dsonar.host=$SONARQUBE_HOST -Dsonar.secretKey=$SONARQUBE_SECRET_KEY
